### ISSUE TITLE
Test fail error (see below for the log error message)

### ISSUE THREAD

**Issue by victorzyang** [CXwudi/comp5903-easy-cucumber#11]
**Describe the bug or Question**
Please see below for the log message of the Test Fail error.

<details><summary>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
SLF4J: Defaulting to no-operation (NOP) logger implementation 
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

scs.comp5903.cucumber.model.exception.EasyCucumberException: EZCU013: Step definition not found for: AndStep(stepString="some step"). Are you sure you implemented this step definition? Or did you forget to make the method public?</summary><p>

Paste your stack trace inside this HTML segment

</p></details>

**(If applicable) Screenshots**

**(For bug report only) Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13, Windows Pro 11]
 - Java version: [e.g. Java 11, Java 17]
 - Maven/Gradle version: [e.g. maven 3.8.2, gradle 7.5.1]
 - IDE: [e.g. IntelliJ Ultimate 2022.2.2, Eclipse 2022.6]

**Anything else**
Add any other context about the problem or question here.

**Comment by CXwudi** [comment]
I think the error message `Are you sure you implemented this step definition? Or did you forget to make the method public?` states it clear that is the step definition implemented?

**Comment by victorzyang** [comment]
Oh right, forgot to mention that I have implemented the step definition in my Step Definition class for the EASY-CUCUMBER tool

**Comment by CXwudi** [comment]
Or maybe you forgot to annotate the method. 

Anyway, can you link the step definition class and the feature file from your private repo?

**Comment by victorzyang** [comment]
Link to my step definition class: https://github.com/victorzyang/5104_Assignment_2/blob/main/src/test/java/com/a1/yahtzeeGame/StepDefSinglePlayerExpCucumber.java

Link to my feature file: https://github.com/victorzyang/5104_Assignment_2/blob/main/src/test/java/com/a1/yahtzeeGame/singlePlayerExpCucumber.feature

**Comment by CXwudi** [comment]
Oh, I see, you can not mismatch a step keyword. 

For example, if you wrote `And a step` in the feature file, you have to use `@JAndStep` or `@JStep` with `ketword = AND`, using any other annotation will be traded as step definition not implemented
